### ISSUE TITLE
관리자 서버 통합 테스트에서 복호화 시 오류 발생

### ISSUE THREAD

**Issue by hyunsb** [FastCampus-Mini5/BE_server#89]
![image](https://github.com/FastCampus-Mini5/BE_server/assets/96504592/417bcead-8018-4937-8130-48170b3533a2)

**Comment by gdtknight** [comment]
해당 내용 확인했고 슬랙으로 기존 암호화 키 전달 완료 !

**Comment by hyunsb** [comment]
해결 완료
